// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	CommentID  int64  `gorm:"column:comment_id;primaryKey;autoIncrement:true" json:"comment_id"` // 评论id
	ID         int64  `gorm:"column:id" json:"id"`                                               // 用户id
	VideoID    int64  `gorm:"column:video_id" json:"video_id"`                                   // 视频id
	Content    string `gorm:"column:content" json:"content"`                                     // 评论
	CreateTime string `gorm:"column:create_time;not null" json:"create_time"`                    // 创建时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
