// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "favorite"

// Favorite mapped from table <favorite>
type Favorite struct {
	FavoriteID int64  `gorm:"column:favorite_id;primaryKey;autoIncrement:true" json:"favorite_id"` // 点赞id
	Username   string `gorm:"column:username" json:"username"`                                     // 用户名
	ID         int64  `gorm:"column:id" json:"id"`                                                 // 用户id
	VideoID    int64  `gorm:"column:video_id" json:"video_id"`                                     // 视频id
	IsDeleted  int32  `gorm:"column:is_deleted" json:"is_deleted"`                                 // 取消点赞
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
