// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "relation"

// Relation mapped from table <relation>
type Relation struct {
	RelationID  int64 `gorm:"column:relation_id;primaryKey;autoIncrement:true" json:"relation_id"` // 关注id
	FollowerID  int64 `gorm:"column:follower_id" json:"follower_id"`                               // 粉丝id
	FollowingID int64 `gorm:"column:following_id" json:"following_id"`                             // 博主id
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
