// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 用户id
	Username        string `gorm:"column:username" json:"username"`                   // 用户名
	FollowCount     int32  `gorm:"column:follow_count" json:"follow_count"`           // 关注总数
	FollowerCount   int32  `gorm:"column:follower_count" json:"follower_count"`       // 粉丝总数
	IsFollow        int32  `gorm:"column:is_follow" json:"is_follow"`                 // 1:未关注,0:已关注
	Password        string `gorm:"column:password" json:"password"`                   // 密码
	Avatar          string `gorm:"column:avatar" json:"avatar"`                       // 用户头像
	BackgroundImage string `gorm:"column:background_image" json:"background_image"`   // 用户个人页顶部大图
	Signature       string `gorm:"column:signature" json:"signature"`                 // 用户个人简介
	TotalFavorited  int32  `gorm:"column:total_favorited" json:"total_favorited"`     // 获赞数量
	WorkCount       int32  `gorm:"column:work_count" json:"work_count"`               // 作品数量
	FavoriteCount   int32  `gorm:"column:favorite_count" json:"favorite_count"`       // 点赞数量
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
